### PR TITLE
Remove focus from ComponentDidMount & ComponentDidUpdate

### PR DESCRIPTION
**Pull request by danlopez**
@chenzihui These focus events aren't necessary, and are leading to some weird behaviors in forms of ours that are using react-tokenizer. Please let me know if there's anything else you'd like me to do here. If not, please merge & bump the version!

### CODE REVIEW

**Comment by danlopez** [comment]
@chenzihui - just to add more detail, here's why this is a problem for us: When a Tokenizer is used inside a connected form, updating a different input changes the state (where we are storing the list of tokens). This triggers a re-render and the `focus` event within ComponentDidUpdate, moving the cursor from the other input to the Tokenizer.

**Comment by chenzihui** [comment]
@danlopez191 good point about multiple input fields. Will merge and bump the version. Thanks!

**Comment by danlopez** [comment]
@chenzihui Thanks, looking forward to using this next release!

**Comment by ypt** [comment]
@chenzihui, thanks! This fix will be very helpful for us. (I work with @danlopez).

**Pull request merged**
